#pragma once

enum class MessageType {
	UNK = 0,
	HELLO = 1,
	SETPLAYERINFO = 2,
	SETSTATSITEMS = 3,
	GETFILE = 4,
	SETFILE = 5,
	SETGAMEINFO = 6,
	SETPLAYEREFFECTS = 7,
	SETINVENTORY = 8,
	SETQUESTS = 9,
	SETNOTES = 10,
	SETRADIO = 11,
	SETWORLDINFO = 12,
	SENDFILEDATA = 13,
	SETMAPMARKERS = 14,
	DOACTION = 15
};